# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180607_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='kind',
            field=models.CharField(choices=[('Python\u6280\u672f', 'Python\u6280\u672f'), ('\u6570\u636e\u5e93\u6280\u672f', '\u6570\u636e\u5e93\u6280\u672f'), ('\u7ecf\u6d4e\u5b66', '\u7ecf\u6d4e\u5b66'), ('\u6587\u4f53\u54a8\u8be2', '\u6587\u4f53\u54a8\u8be2'), ('\u4e2a\u4eba\u5fc3\u60c5', '\u4e2a\u4eba\u5fc3\u60c5'), ('\u5176\u4ed6', '\u5176\u4ed6')], default=('Python\u6280\u672f', 'Python\u6280\u672f'), max_length=20),
        ),
    ]
